#!/usr/bin/env bash
#Display inifinity and beyond

cleanup() {
	rm -f "/var/run/myscript.pid"
	exit 0
}

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup' SIGQUIT

echo $$ > "/var/run/myscript.pid"

while true
do
	sleep 1
done
