#!/usr/bin/env bash
#This is an init script

FILE="/var/run/my_process.pid"

start() {
	if [ "$FILE" ]
	then
		echo "manage_my_process is already running"
	else
		echo "starting manage_my_process..."
		/bin/bash/path/to/manage_my_process &
		echo "$!" > "$FILE"
		echo "manage_my_process started"
	fi
}

stop() {
	if [ -f "$FILE" ]
	then
		echo "stopping manage_my_process..."
		kill "$(cut "$FILE")"
		rm -f "$FILE"	
		echo "manage_my_process stopped."
	else
		echo "manage_my_process is not running."
	fi
}

restart() {
	stop
	start
	echo "manage_my_process restarted."
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	*)
	echo "usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
exit 0
