#!/usr/bin/env bash
#fizzbuzz bash script

#Initialize the counter var
i=1

#looping condition
while [ $i -lt 101 ]
do
	if [ $((i%15)) = 0 ]
	then
		echo "Fizzbuzz"
	elif [ $((i%3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((i%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i+1))
done
