#!/usr/bin/env bash
# A while loop that prints Best School ten times


#initialize a counter
i=0

#The looping condition
while [ $i -lt 10 ]
do
	echo "Best School"

	#counter increament
	i=$((i + 1))
done
