#!/usr/bin/env bash
# An until loop that prints best School ten times


#Initialize a counter
i=0

#The until looping condition
until [ $i -ge 10 ]
do
	echo "Best School"

	#increment the counter
	i=$((i + 1))
done
