#!/usr/bin/env bash
#Displays best school ten times
# on the 9th itreration, displays best school, Hi on a new line

count='0'

while [ $count -lt 10 ]
do
	echo 'Best School'
if [ $count -eq 8 ]
then
	echo 'Hi'
fi
	count=$((count+1))
done
