#!/usr/bin/env bash
#Displays bad luck on the 4th loop
#Displays good luck on the 8th loop

i="0"
while [ $i -lt 10 ]
do
if [ $i -eq 3 ];
then
    echo "bad luck"
elif [ $i -eq 7 ];
then
    echo "good luck"
else
    echo "Best School"
fi
i=$((i+1))
done
