#!/usr/bin/env bash
# A bash script that iterates from 1 to 20

#Initialize a counter
i=1

#looping conditions
while [ $i -lt 21 ]
do
	case $i in
		4)
		echo $i
		echo "bad luck from China"
		;;

		9)
		echo $i
		echo "bad luck from Japan"
		;;

		17)
		echo $i
		echo "bad luck from Italy"
		;;

		*)
		echo $i
		;;
	esac
		#Increment counter
		i=$((i + 1))
done
