#!/usr/bin/env bash
#displays bad luch from china, japan, Italy
#on line 4, 9 and 17 respectively

count='1'

while [ $count -le 20 ]
do
case $count  in
	4) echo $count
	echo 'bad luck from china'
	;;
	9) echo $count
	echo 'bad luck from japan'
	;;
	17) echo $count
	echo 'bad luck from italy'
	;;
	*)
	echo $count
	esac
		count=$((count+1))
done
