#!/usr/bin/env bash
#Displays the time of 12 hours and 59 minutes

HOURS=0

while [ $HOURS -le 12 ]
do
	echo "Hour: $HOURS"
	for minute in {1..59}
	do
		echo "$minute"
	done
	HOURS=$((HOURS + 1))
done
